# Site settings
title: MrRice
#baseurl 直接注释调的话  在本地和线上都正常，但是如果打开  则会冲突，本地的/blog可以访问 但是到线上要  /
#baseurl: "/blog" #本地
#baseurl: "/" #线上
url: "mrrice.top"
#url: "https://mrrice996.github.io/mrrice.github.io/"

# User settings
username: MrRice
user_title: Java is the best language
user_description: Java is the best language in the world
email: mailTo:mrrice1202@163.com
github: https://github.com/MrRice996
#twitter_username: lorem_ipsum
#gplus_username:  lorem_ipsum

# Google-analytics  google提供的网站数据统计功能
google-analytics:
  id: ""

#转换时排除某些文件、文件夹 ['package.json', 'src' , 'node_modules']
#exclude: ['package.json', 'src' , 'node_modules']

