# Site settings
title: MrRice
baseurl: "/"
url: "https://mrrice996.github.io/mrrice.github.io/"

# User settings
username: MrRice
user_title: Java is the best language
user_description: Java is the best language in the world
#email: mrrice1202@163.com
#twitter_username: lorem_ipsum
#github_username: MrRice996
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

#转换时排除某些文件、文件夹 ['package.json', 'src' , 'node_modules']
#exclude: ['']

